import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
import ReduxProvider from "@/utils/redux/providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  weight: ["400", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}
      >
        <Toaster
          toastOptions={{
            style: {
              backgroundColor: "rgba(32, 29, 87)",
              color: "white",
            },
          }}
        />
        <ReduxProvider>
            <div className="">
              <Nav />
              {children}
              <Footer />
            </div>
        </ReduxProvider>

      </body>
    </html>
  );
}
